services:
  crm-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
      - DB_USERNAME=postgres.cyohgfityjrccegxuftb
      - DB_PASSWORD=CRM-Inteligente
      - PORT=8080
    restart: always
